### ISSUE TITLE
p4c crash when table action has run-time parameter containing function call

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#2321]
I thought of writing an example P4_16 program like the attached one, while thinking about this issue: https://github.com/p4lang/p4-spec/issues/830

That issue so far has concerned itself with table key expressions that have side effects.

Another source of side effects in the definition of a table is its actions.  Of course the very common way this is done is for an action to assign values to variables/fields that are visible in the lexical scope of the action definition.  The attached example program doesn't raise any interesting issues related to that (at least not that I have thought of).

Another way for an action to cause side effects is to have a direction `in` parameter to an action, where it is required that a run-time expression returning a value of that type must be given in a table's action list, if you wish to use that action for that table.  Such a run-time expression could be a function (extern function, extern method call, or normal P4_16 function) that has side effects (in the case of an extern) or assigns values to its direction `out` or `inout` parameters (for any of those 3 kinds of calls).

Here is the relevant interesting part of the attached example program:
```
bit<16> bump_val(inout bit<16> x) {
    x = x | 7;
    return (x >> 1);
}

// ... later ...

    action a2(in bit<16> y, in bit<16> z) {
        hdr.ethernet.srcAddr[15:0] = y + z;
    }
    table t1 {
        key = {
            hdr.ethernet.srcAddr : exact;
        }
        actions = {
            a1(hdr.ethernet.dstAddr);
            a2(bump_val(hdr.ethernet.etherType), bump_val(hdr.ethernet.etherType));  // <-- this line is the trouble-maker
            my_drop;
            NoAction;
        }
        const default_action = NoAction;
    }
```
The line marked as the trouble-maker is the one causing the p4c compiler bug, probably because of an unhandled case since this kind of code was not expected.  It seems to compile to correct code if you eliminate the calls to `bump_val`.

Currently this kind of program causes p4c to give a Compiler bug message:
```
$ p4c --version
p4c 1.2.0 (SHA: e9ecc7ef)

$ p4c --target bmv2 --arch v1model table-with-side-effecting-action-parameters2.p4
In file: /home/andy/p4c/frontends/p4/functionsInlining.cpp:41
Compiler Bug: /home/andy/p4c/frontends/p4/functionsInlining.cpp:41: Null stat
```

This issue is like https://github.com/p4lang/p4-spec/issues/830, but unlike the proposed PR https://github.com/p4lang/p4-spec/pull/834 that proposes that table key expressions with side effects be evaluated as if they are all done before the `my_table.apply()` call, it is not so obvious to me whether there is always such a straightforward transformation of the source code of examples like the attached program that are equivalent in behavior.

If there is a way to do it, I suspect that it would involve moving the side-effecting expressions into the body of the action, but there could be subtleties that I am missing with that idea.  I believe it is how p4c currently handles run-time expressions that do not have side effects -- i.e. it moves them into the body of the action (or perhaps a new unique action just for this table, created from the one in the source code, because other tables might also use the action with a different run-time expression as the parameter).

[table-with-side-effecting-action-parameters2.p4.txt](https://github.com/p4lang/p4c/files/4490221/table-with-side-effecting-action-parameters2.p4.txt)

**Comment by jafingerhut** [comment]
As a minor follow-up to the main issue, it seems much more constrained in the language to attempt to cause this kind of issue with an action that has direction `out` or `inout` parameters, because such an expression must be an L-value, and there are fewer kinds of L-value expressions that can cause side effects.  For example, an extern call cannot return an L-value, so they cannot be used as the entire expression that is the action parameter at the action call site.  Neither can a normal P4_16 function return an L-value.

You could have an L-value like `my_hdr_stack[expr].field` where `expr` contained a call to an extern function, extern method, or normal P4_16 function, though, and just like in the example program, any of those might have side effects.

Are there any other P4_16 L-value expressions that can contain function/method calls within them?

**Comment by mbudiu-vmw** [comment]
I think this is the same is #2266.

**Comment by jafingerhut** [comment]
Yes, looks like it could be.  The language specification questions of whether to allow this, and if so, defining how it is supposed to behave, remains.

**Comment by fruffy** [comment]
@mbudiu-vmw Is this also fixed now?

**Comment by mbudiu-vmw** [comment]
Let me check by adding this extra test.

**Comment by jafingerhut** [comment]
Sorry, I reopened this thinking that the original test program still failed with the latest p4c, but it appears that the compiler no longer gives a compiler bug for that test program, and even seems to produce output from the mid-end that is correct.  I will open a separate issue with similar but different test programs that do cause a compiler bug with the latest version of p4c.
