### ISSUE TITLE
PNA and PSA DPDK tests should not be run by `check-p4` target

### ISSUE THREAD

**Issue by kfcripps** [p4lang/p4c#4614]
With the following `cmake` options:
```
cmake ../../../ -G Ninja -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=. -DENABLE_BMV2=OFF -DENABLE_EBPF=OFF -DENABLE_UBPF=OFF -DENABLE_DPDK=OFF -DENABLE_P4TEST=ON -DENABLE_GC=ON -DENABLE_P4TC=OFF
ninja -j4
```
`check-p4` fails because `check-p4` still runs the `pna-*` and `psa-*` DPDK tests in `testdata/p4_16_samples/`. `backend/p4test/CMakeLists.txt`:
```
set (P4TEST_SUITES
  "${P4C_SOURCE_DIR}/testdata/p4_16_samples/*.p4"
  ...
```

and in `backend/dpdk/CMakeLists.txnt`:
```
set (P4_16_SUITES
  "${P4C_SOURCE_DIR}/testdata/p4_16_samples/psa-*.p4"
  "${P4C_SOURCE_DIR}/testdata/p4_16_samples/pna-*.p4"
  ...
 p4c_add_tests("dpdk" ${DPDK_COMPILER_DRIVER} "${P4_16_SUITES}" "" "--bfrt")
```

The below tests under `check-p4` are failing:
```
The following tests FAILED:
        823 - p4/testdata/p4_16_samples/pna-dpdk-bvec_union.p4 (Failed)
        824 - p4/testdata/p4_16_samples/pna-dpdk-bvec_union_dpdk.p4 (Failed)
        827 - p4/testdata/p4_16_samples/pna-dpdk-direct-meter-learner.p4 (Failed)
        828 - p4/testdata/p4_16_samples/pna-dpdk-flatten-local-struct-decl.p4 (Failed)
        830 - p4/testdata/p4_16_samples/pna-dpdk-header-union-stack.p4 (Failed)
        831 - p4/testdata/p4_16_samples/pna-dpdk-header-union-stack1.p4 (Failed)
        832 - p4/testdata/p4_16_samples/pna-dpdk-header-union-stack2.p4 (Failed)
        833 - p4/testdata/p4_16_samples/pna-dpdk-invalid-hdr-warnings5.p4 (Failed)
        834 - p4/testdata/p4_16_samples/pna-dpdk-invalid-hdr-warnings6.p4 (Failed)
        835 - p4/testdata/p4_16_samples/pna-dpdk-parser-state-err.p4 (Failed)
        836 - p4/testdata/p4_16_samples/pna-dpdk-parser-wrong-arith.p4 (Failed)
        837 - p4/testdata/p4_16_samples/pna-dpdk-small_sample.p4 (Failed)
        844 - p4/testdata/p4_16_samples/pna-dpdk-table-key-use-annon.p4 (Failed)
        845 - p4/testdata/p4_16_samples/pna-dpdk-toeplitz-hash-1.p4 (Failed)
        846 - p4/testdata/p4_16_samples/pna-dpdk-toeplitz-hash.p4 (Failed)
        847 - p4/testdata/p4_16_samples/pna-dpdk-union-bmv2.p4 (Failed)
        848 - p4/testdata/p4_16_samples/pna-dpdk-wrong-warning.p4 (Failed)
        849 - p4/testdata/p4_16_samples/pna-elim-hdr-copy-dpdk.p4 (Failed)
        855 - p4/testdata/p4_16_samples/pna-example-dpdk-varbit-1.p4 (Failed)
        856 - p4/testdata/p4_16_samples/pna-example-dpdk-varbit.p4 (Failed)
        859 - p4/testdata/p4_16_samples/pna-example-ipsec.p4 (Failed)
        881 - p4/testdata/p4_16_samples/pna-too-big-label-name-dpdk.p4 (Failed)
        918 - p4/testdata/p4_16_samples/psa-dpdk-checksum-arg-header.p4 (Failed)
        925 - p4/testdata/p4_16_samples/psa-dpdk-large-header-fields.p4 (Failed)
        926 - p4/testdata/p4_16_samples/psa-dpdk-large-struct-fields.p4 (Failed)
        941 - p4/testdata/p4_16_samples/psa-dpdk-table-entries-exact-ternary.p4 (Failed)
        965 - p4/testdata/p4_16_samples/psa-dpdk-tmp-mask-align.p4 (Failed)
        973 - p4/testdata/p4_16_samples/psa-example-dpdk-byte-alignment_1.p4 (Failed)
        974 - p4/testdata/p4_16_samples/psa-example-dpdk-byte-alignment_2.p4 (Failed)
        975 - p4/testdata/p4_16_samples/psa-example-dpdk-byte-alignment_3.p4 (Failed)
        977 - p4/testdata/p4_16_samples/psa-example-dpdk-byte-alignment_5.p4 (Failed)
        978 - p4/testdata/p4_16_samples/psa-example-dpdk-byte-alignment_6.p4 (Failed)
        979 - p4/testdata/p4_16_samples/psa-example-dpdk-byte-alignment_7.p4 (Failed)
        980 - p4/testdata/p4_16_samples/psa-example-dpdk-byte-alignment_8.p4 (Failed)
        981 - p4/testdata/p4_16_samples/psa-example-dpdk-byte-alignment_9.p4 (Failed)
        982 - p4/testdata/p4_16_samples/psa-example-dpdk-counter.p4 (Failed)
        983 - p4/testdata/p4_16_samples/psa-example-dpdk-directmeter.p4 (Failed)
        984 - p4/testdata/p4_16_samples/psa-example-dpdk-externs.p4 (Failed)
        985 - p4/testdata/p4_16_samples/psa-example-dpdk-local-variable.p4 (Failed)
        986 - p4/testdata/p4_16_samples/psa-example-dpdk-meter-execute-err.p4 (Failed)
        987 - p4/testdata/p4_16_samples/psa-example-dpdk-meter.p4 (Failed)
        988 - p4/testdata/p4_16_samples/psa-example-dpdk-meter1.p4 (Failed)
```

**Comment by fruffy** [comment]
A little odd that they fail considering p4test is target-agnostic. What is the exact error message?

**Comment by kfcripps** [comment]
@fruffy For example:
```
Error compiling
pna-dpdk-wrong-warning.p4:2:10: fatal error: dpdk/pna.p4: No such file or directory
    2 | #include <dpdk/pna.p4>
      |          ^~~~~~~~~~~~~
compilation terminated.
[--Werror=I/O error] error: Preprocessor returned exit code 256; aborting compilation
[--Werror=overlimit] error: 1 errors encountered, aborting compilation

<end of output>
Test time =   0.16 sec
----------------------------------------------------------
Test Failed.
```

**Comment by fruffy** [comment]
I see, this seems like an include problem: https://github.com/p4lang/p4c/blob/main/CMakeLists.txt#L537

It is nice to have more programs to test on for the compiler, but if users want that back end disable these programs should be disabled, true.

**Comment by kfcripps** [comment]
#4615 Disables _all_ pna and psa tests for `check-p4`, but only 41 were failing previously. Maybe they shouldn't all be disabled? @fruffy How to distinguish between target-specific and target-agnostic `pna-*` and `psa-*` tests?

**Comment by fruffy** [comment]
They are all target-specific, the problem is that, because https://github.com/p4lang/p4c/blob/main/CMakeLists.txt#L546 is disabled, the include files are not exported correctly. 

The other tests pass because they use `#include <pna.p4>` instead of `#include <dpdk/pna.p4>`. That file is always exported. Same for psa. You can distinguish the tests by checking whether they have the dpdk prefix.

Effectively, there is BMv2 PNA and PSA and DPDK PSA and PNA. I believe the the BMv2 PNA is not classified correctly. 

I think all of this is a little messy, but I do not have an immediate answer how to clean this up.

**Comment by jafingerhut** [comment]
+ DPDK PSA is not 100% feature-complete, but it is way more featureful than BMv2 PSA
+ DPDK PNA is not 100% feature-complete, but a lot of things work
+ BMv2 PSA had work last done on it 4 or 5 years ago, and even very simple programs either give compile-time errors, or silently produce output that is not functionally correct.  The few test cases checked into the p4c repo should be working correctly, but they are all pretty simple small programs.
+ BMv2 PNA does not exist.  There are some open PRs right now to create it, but as far as I know not merged yet.

**Comment by jafingerhut** [comment]
I have not thought much about what to recommend for a test directory and/or file naming convention that would be clearest for all of these combinations.

I believe part of how we reached the current state is that some people were hoping that PSA architecture test programs could be put into the testdata/p4_16_samples directory, and they should work the same on any implementation of PSA, whether that was BMv2, DPDK, etc.  In reality each of the PSA implementations is partial, and therefore there are PSA test programs that work on some implementations but not others, because of the different feature subsets those implementations have.

I expect the same will be true of PNA implementations in this repo, for a long time, e.g. perhaps always.

One possibility would be to have a separate test directory for each target/architecture combination.  Some might worry about the duplication of same or similar test programs for the same architecture for different targets, but I think the separation of management of the set of test programs for each target/arch combo might help ease deciding where each test program should be placed.

**Comment by fruffy** [comment]
> * DPDK PSA is not 100% feature-complete, but it is way more featureful than BMv2 PSA
> 
>     * DPDK PNA is not 100% feature-complete, but a lot of things work
> 
>     * BMv2 PSA had work last done on it 4 or 5 years ago, and even very simple programs either give compile-time errors, or silently produce output that is not functionally correct.  The few test cases checked into the p4c repo should be working correctly, but they are all pretty simple small programs.
> 
>     * BMv2 PNA does not exist.  There are some open PRs right now to create it, but as far as I know not merged yet.

I am not sure whether the existing programs which only include `<pna.p4>` were meant for BMv2 or the DPDK target. If they were meant for the latter we should fix the includes.

**Comment by jafingerhut** [comment]
Would it help if some time in the next week or so I tried categorizing how the current p4c test programs are used, broken down by whether they include v1model.p4, psa.p4, or pna.p4 ?  I am guessing there are probably only a few combinations of ways each program is used during current testing, and it might help give ideas on what we may want to change.

**Comment by kfcripps** [comment]
> They are all target-specific, the problem is that, because https://github.com/p4lang/p4c/blob/main/CMakeLists.txt#L546 is disabled, the include files are not exported correctly.

I tried moving [these lines](https://github.com/p4lang/p4c/blob/main/CMakeLists.txt#L549-L550) above to the `update_includes` target, but that did not fix the failing tests

**Comment by kfcripps** [comment]
Oops, I forgot to create the `dpdk` directory ;), so the following diff fixes the failing tests:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d6c6b0d07..0e9314e7b 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -539,18 +539,13 @@ add_custom_target(update_includes ALL
   COMMAND ${CMAKE_COMMAND} -E copy_if_different ${P4C_SOURCE_DIR}/p4include/*.p4 ${P4C_BINARY_DIR}/p4include
   COMMAND ${CMAKE_COMMAND} -E make_directory ${P4C_BINARY_DIR}/p4include/bmv2
   COMMAND ${CMAKE_COMMAND} -E copy_if_different ${P4C_SOURCE_DIR}/p4include/bmv2/psa.p4 ${P4C_BINARY_DIR}/p4include/bmv2
+  COMMAND ${CMAKE_COMMAND} -E make_directory ${P4C_BINARY_DIR}/p4include/dpdk
+  COMMAND ${CMAKE_COMMAND} -E copy_if_different ${P4C_SOURCE_DIR}/p4include/dpdk/psa.p4 ${P4C_BINARY_DIR}/p4include/dpdk
+  COMMAND ${CMAKE_COMMAND} -E copy_if_different ${P4C_SOURCE_DIR}/p4include/dpdk/pna.p4 ${P4C_BINARY_DIR}/p4include/dpdk
   COMMAND for h in ${OTHER_HEADERS} \; do
     ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_SOURCE_DIR}/\$$h ${P4C_BINARY_DIR}/p4include \;
   done
   )
-if (ENABLE_DPDK)
-add_custom_target(dpdk_includes ALL
-  COMMAND ${CMAKE_COMMAND} -E make_directory ${P4C_BINARY_DIR}/p4include/dpdk
-  COMMAND ${CMAKE_COMMAND} -E copy_if_different ${P4C_SOURCE_DIR}/p4include/dpdk/psa.p4 ${P4C_BINARY_DIR}/p4include/dpdk
-  COMMAND ${CMAKE_COMMAND} -E copy_if_different ${P4C_SOURCE_DIR}/p4include/dpdk/pna.p4 ${P4C_BINARY_DIR}/p4include/dpdk
-  DEPENDS update_includes
-)
-endif()
```

**Comment by kfcripps** [comment]
If the above is all that is needed to fix the failing tests, then I think it's fine to run the dpdk tests under the `check-p4` testing target (the same is done for the bmv2 tests and bmv2 p4include files already). I have updated #4615 accordingly.

**Comment by fruffy** [comment]
> Would it help if some time in the next week or so I tried categorizing how the current p4c test programs are used, broken down by whether they include v1model.p4, psa.p4, or pna.p4 ? I am guessing there are probably only a few combinations of ways each program is used during current testing, and it might help give ideas on what we may want to change. (or perhaps the author of this PR has already done so?)

Yes, that would be great!
